from aim_fsm import *

class GPT_test(StateMachineProgram):
    class SpeakResponse(Say):
      def start(self,event):
        self.text = event.response
        super().start(event)
        
    def setup(self):
        #       Say("Talk to me") =C=> loop
        # 
        #       loop: StateNode() =Hear()=> AskGPT() =OpenAITrans()=> self.SpeakResponse() =C=> loop
        
        # Code generated by genfsm on Sun Jan  5 20:36:53 2025:
        
        say1 = Say("Talk to me") .set_name("say1") .set_parent(self)
        loop = StateNode() .set_name("loop") .set_parent(self)
        askgpt1 = AskGPT() .set_name("askgpt1") .set_parent(self)
        speakresponse1 = self.SpeakResponse() .set_name("speakresponse1") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(say1) .add_destinations(loop)
        
        heartrans1 = HearTrans() .set_name("heartrans1")
        heartrans1 .add_sources(loop) .add_destinations(askgpt1)
        
        openaitrans1 = OpenAITrans() .set_name("openaitrans1")
        openaitrans1 .add_sources(askgpt1) .add_destinations(speakresponse1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(speakresponse1) .add_destinations(loop)
        
        return self

