from aim_fsm import *

class GPT_test(StateMachineProgram):

    class CheckResponse(StateNode):
        def start(self, event):
            super().start(event)
            response = event.response
            if response.startswith('#'):
                commands = response.split('\n')
                self.post_event(DataEvent(commands))
            else:
                self.post_event(DataEvent(response))

    class CmdForward(Forward):
      def start(self,event):
        self.distance_mm = float((event.data.split(' '))[1])
        super().start(event)

    class CmdSideways(Sideways):
      def start(self,event):
        self.distance_mm = float((event.data.split(' '))[1])
        super().start(event)

    class CmdTurn(Turn):
      def start(self,event):
        self.angle_deg = float((event.data.split(' '))[1])
        super().start(event)

    class SpeakResponse(Say):
      def start(self,event):
        self.text = event.data
        super().start(event)
        
    def setup(self):
        #       Say("Talk to me") =C=> loop
        # 
        #       loop: StateNode() =Hear()=> AskGPT() =OpenAITrans()=> check
        # 
        #       check: self.CheckResponse()
        #       check =D(list)=> dispatch
        #       check =D(str)=> self.SpeakResponse() =C=> loop
        # 
        #       dispatch: Iterate()
        #       dispatch =D(re.compile('#forward'))=> self.CmdForward() =CNext=> dispatch
        #       dispatch =D(re.compile('#sideways'))=> self.CmdSideways() =CNext=> dispatch
        #       dispatch =D(re.compile('#turn'))=> self.CmdTurn() =CNext=> dispatch
        #       dispatch =D()=> Print() =Next=> dispatch
        #       dispatch =C=> loop
        
        # Code generated by genfsm on Tue Jan  7 19:22:40 2025:
        
        say1 = Say("Talk to me") .set_name("say1") .set_parent(self)
        loop = StateNode() .set_name("loop") .set_parent(self)
        askgpt1 = AskGPT() .set_name("askgpt1") .set_parent(self)
        check = self.CheckResponse() .set_name("check") .set_parent(self)
        speakresponse1 = self.SpeakResponse() .set_name("speakresponse1") .set_parent(self)
        dispatch = Iterate() .set_name("dispatch") .set_parent(self)
        cmdforward1 = self.CmdForward() .set_name("cmdforward1") .set_parent(self)
        cmdsideways1 = self.CmdSideways() .set_name("cmdsideways1") .set_parent(self)
        cmdturn1 = self.CmdTurn() .set_name("cmdturn1") .set_parent(self)
        print1 = Print() .set_name("print1") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(say1) .add_destinations(loop)
        
        heartrans1 = HearTrans() .set_name("heartrans1")
        heartrans1 .add_sources(loop) .add_destinations(askgpt1)
        
        openaitrans1 = OpenAITrans() .set_name("openaitrans1")
        openaitrans1 .add_sources(askgpt1) .add_destinations(check)
        
        datatrans1 = DataTrans(list) .set_name("datatrans1")
        datatrans1 .add_sources(check) .add_destinations(dispatch)
        
        datatrans2 = DataTrans(str) .set_name("datatrans2")
        datatrans2 .add_sources(check) .add_destinations(speakresponse1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(speakresponse1) .add_destinations(loop)
        
        datatrans3 = DataTrans(re.compile('#forward')) .set_name("datatrans3")
        datatrans3 .add_sources(dispatch) .add_destinations(cmdforward1)
        
        cnexttrans1 = CNextTrans() .set_name("cnexttrans1")
        cnexttrans1 .add_sources(cmdforward1) .add_destinations(dispatch)
        
        datatrans4 = DataTrans(re.compile('#sideways')) .set_name("datatrans4")
        datatrans4 .add_sources(dispatch) .add_destinations(cmdsideways1)
        
        cnexttrans2 = CNextTrans() .set_name("cnexttrans2")
        cnexttrans2 .add_sources(cmdsideways1) .add_destinations(dispatch)
        
        datatrans5 = DataTrans(re.compile('#turn')) .set_name("datatrans5")
        datatrans5 .add_sources(dispatch) .add_destinations(cmdturn1)
        
        cnexttrans3 = CNextTrans() .set_name("cnexttrans3")
        cnexttrans3 .add_sources(cmdturn1) .add_destinations(dispatch)
        
        datatrans6 = DataTrans() .set_name("datatrans6")
        datatrans6 .add_sources(dispatch) .add_destinations(print1)
        
        nexttrans1 = NextTrans() .set_name("nexttrans1")
        nexttrans1 .add_sources(print1) .add_destinations(dispatch)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(dispatch) .add_destinations(loop)
        
        return self
