import vex

from .nodes import *
from .transitions import *

#---------------- Emotion Macros from VEXCode ----------------

class ActHappy(ActionNode):
    def setup(self):
        #         ShowEmoji(vex.EmojiType.HAPPY)                                =T(0.5)=>
        # 	PlaySound(vex.SoundType.ACT_HAPPY)                            =T(0.115)=>
        #         ShowEmoji(vex.EmojiType.HAPPY, vex.EmojiLookType.LOOK_RIGHT)  =N=>
        # 	Glow(vex.Color.YELLOW)                                        =N=>
        #         Turn(-4, 100)                                                 =C=>
        # 	Glow(vex.Color.WHITE)                                         =N=>
        #         ShowEmoji(vex.EmojiType.HAPPY, vex.EmojiLookType.LOOK_LEFT)   =N=>
        #         Turn(8, 100)                                                  =C=>
        # 	Glow(vex.Color.YELLOW)                                        =N=>
        #         ShowEmoji(vex.EmojiType.HAPPY, vex.EmojiLookType.LOOK_RIGHT)  =N=>
        #         Turn(-4, 100)                                                 =C=>
        # 	StateNode()                                                   =T(0.1)=> loop
        # 
        #         loop: Iterate(3)
        # 	loop =D=> 
        #           ShowEmoji(vex.EmojiType.QUIET)                              =N=>
        #   	  Glow(vex.Color.WHITE)                                       =N=>
        #           MoveFor(1, 90)                                              =C=>
        #           ShowEmoji(vex.EmojiType.HAPPY)                              =N=>
        #           Glow(vex.Color.YELLOW)                                      =N=>
        #           MoveFor(1, -90)                                             =CNext=> loop
        # 	loop =C=> finish
        # 
        #         finish: Glow(vex.Color.TRANSPARENT) =T(0.5)=> ParentCompletes()
        # 
        
        # Code generated by genfsm on Wed May 28 22:20:11 2025:
        
        showemoji1 = ShowEmoji(vex.EmojiType.HAPPY) .set_name("showemoji1") .set_parent(self)
        playsound1 = PlaySound(vex.SoundType.ACT_HAPPY) .set_name("playsound1") .set_parent(self)
        showemoji2 = ShowEmoji(vex.EmojiType.HAPPY, vex.EmojiLookType.LOOK_RIGHT) .set_name("showemoji2") .set_parent(self)
        glow1 = Glow(vex.Color.YELLOW) .set_name("glow1") .set_parent(self)
        turn1 = Turn(-4, 100) .set_name("turn1") .set_parent(self)
        glow2 = Glow(vex.Color.WHITE) .set_name("glow2") .set_parent(self)
        showemoji3 = ShowEmoji(vex.EmojiType.HAPPY, vex.EmojiLookType.LOOK_LEFT) .set_name("showemoji3") .set_parent(self)
        turn2 = Turn(8, 100) .set_name("turn2") .set_parent(self)
        glow3 = Glow(vex.Color.YELLOW) .set_name("glow3") .set_parent(self)
        showemoji4 = ShowEmoji(vex.EmojiType.HAPPY, vex.EmojiLookType.LOOK_RIGHT) .set_name("showemoji4") .set_parent(self)
        turn3 = Turn(-4, 100) .set_name("turn3") .set_parent(self)
        statenode1 = StateNode() .set_name("statenode1") .set_parent(self)
        loop = Iterate(3) .set_name("loop") .set_parent(self)
        showemoji5 = ShowEmoji(vex.EmojiType.QUIET) .set_name("showemoji5") .set_parent(self)
        glow4 = Glow(vex.Color.WHITE) .set_name("glow4") .set_parent(self)
        movefor1 = MoveFor(1, 90) .set_name("movefor1") .set_parent(self)
        showemoji6 = ShowEmoji(vex.EmojiType.HAPPY) .set_name("showemoji6") .set_parent(self)
        glow5 = Glow(vex.Color.YELLOW) .set_name("glow5") .set_parent(self)
        movefor2 = MoveFor(1, -90) .set_name("movefor2") .set_parent(self)
        finish = Glow(vex.Color.TRANSPARENT) .set_name("finish") .set_parent(self)
        parentcompletes1 = ParentCompletes() .set_name("parentcompletes1") .set_parent(self)
        
        timertrans1 = TimerTrans(0.5) .set_name("timertrans1")
        timertrans1 .add_sources(showemoji1) .add_destinations(playsound1)
        
        timertrans2 = TimerTrans(0.115) .set_name("timertrans2")
        timertrans2 .add_sources(playsound1) .add_destinations(showemoji2)
        
        nulltrans1 = NullTrans() .set_name("nulltrans1")
        nulltrans1 .add_sources(showemoji2) .add_destinations(glow1)
        
        nulltrans2 = NullTrans() .set_name("nulltrans2")
        nulltrans2 .add_sources(glow1) .add_destinations(turn1)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(turn1) .add_destinations(glow2)
        
        nulltrans3 = NullTrans() .set_name("nulltrans3")
        nulltrans3 .add_sources(glow2) .add_destinations(showemoji3)
        
        nulltrans4 = NullTrans() .set_name("nulltrans4")
        nulltrans4 .add_sources(showemoji3) .add_destinations(turn2)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(turn2) .add_destinations(glow3)
        
        nulltrans5 = NullTrans() .set_name("nulltrans5")
        nulltrans5 .add_sources(glow3) .add_destinations(showemoji4)
        
        nulltrans6 = NullTrans() .set_name("nulltrans6")
        nulltrans6 .add_sources(showemoji4) .add_destinations(turn3)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(turn3) .add_destinations(statenode1)
        
        timertrans3 = TimerTrans(0.1) .set_name("timertrans3")
        timertrans3 .add_sources(statenode1) .add_destinations(loop)
        
        datatrans1 = DataTrans() .set_name("datatrans1")
        datatrans1 .add_sources(loop) .add_destinations(showemoji5)
        
        nulltrans7 = NullTrans() .set_name("nulltrans7")
        nulltrans7 .add_sources(showemoji5) .add_destinations(glow4)
        
        nulltrans8 = NullTrans() .set_name("nulltrans8")
        nulltrans8 .add_sources(glow4) .add_destinations(movefor1)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(movefor1) .add_destinations(showemoji6)
        
        nulltrans9 = NullTrans() .set_name("nulltrans9")
        nulltrans9 .add_sources(showemoji6) .add_destinations(glow5)
        
        nulltrans10 = NullTrans() .set_name("nulltrans10")
        nulltrans10 .add_sources(glow5) .add_destinations(movefor2)
        
        cnexttrans1 = CNextTrans() .set_name("cnexttrans1")
        cnexttrans1 .add_sources(movefor2) .add_destinations(loop)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(loop) .add_destinations(finish)
        
        timertrans4 = TimerTrans(0.5) .set_name("timertrans4")
        timertrans4 .add_sources(finish) .add_destinations(parentcompletes1)
        
        return self

class ActSad(ActionNode):
    def setup(self):
        #         ShowEmoji(vex.EmojiType.SAD)                                  =T(0.5)=>
        # 	PlaySound(vex.SoundType.ACT_SAD)                              =T(0.115)=>
        # 	Glow(vex.LightType.ALL_LEDS, 0, 0, 250)                       =N=>
        #         ShowEmoji(vex.EmojiType.SAD, vex.EmojiLookType.LOOK_RIGHT)    =N=>
        #         MoveFor(11, -315, 70)                                         =C=>
        # 	Glow(vex.LightType.ALL_LEDS, 0, 0, 50)                        =N=>
        #         ShowEmoji(vex.EmojiType.SAD, vex.EmojiLookType.LOOK_LEFT)     =N=>
        #         MoveFor(11, -225, 70)                                         =C=>
        # 	Glow(vex.LightType.ALL_LEDS, 0, 0, 10)                        =N=>
        #         ShowEmoji(vex.EmojiType.SAD, vex.EmojiLookType.LOOK_FORWARD)  =N=>
        #         MoveFor(11, -45, 70)                                          =C=>
        #         StateNode()                                                   =T(0.5)=>
        #         Glow(vex.LightType.ALL_LEDS, vex.Color.TRANSPARENT)           =N=>
        #         ParentCompletes()
        
        # Code generated by genfsm on Wed May 28 22:20:11 2025:
        
        showemoji7 = ShowEmoji(vex.EmojiType.SAD) .set_name("showemoji7") .set_parent(self)
        playsound2 = PlaySound(vex.SoundType.ACT_SAD) .set_name("playsound2") .set_parent(self)
        glow6 = Glow(vex.LightType.ALL_LEDS, 0, 0, 250) .set_name("glow6") .set_parent(self)
        showemoji8 = ShowEmoji(vex.EmojiType.SAD, vex.EmojiLookType.LOOK_RIGHT) .set_name("showemoji8") .set_parent(self)
        movefor3 = MoveFor(11, -315, 70) .set_name("movefor3") .set_parent(self)
        glow7 = Glow(vex.LightType.ALL_LEDS, 0, 0, 50) .set_name("glow7") .set_parent(self)
        showemoji9 = ShowEmoji(vex.EmojiType.SAD, vex.EmojiLookType.LOOK_LEFT) .set_name("showemoji9") .set_parent(self)
        movefor4 = MoveFor(11, -225, 70) .set_name("movefor4") .set_parent(self)
        glow8 = Glow(vex.LightType.ALL_LEDS, 0, 0, 10) .set_name("glow8") .set_parent(self)
        showemoji10 = ShowEmoji(vex.EmojiType.SAD, vex.EmojiLookType.LOOK_FORWARD) .set_name("showemoji10") .set_parent(self)
        movefor5 = MoveFor(11, -45, 70) .set_name("movefor5") .set_parent(self)
        statenode2 = StateNode() .set_name("statenode2") .set_parent(self)
        glow9 = Glow(vex.LightType.ALL_LEDS, vex.Color.TRANSPARENT) .set_name("glow9") .set_parent(self)
        parentcompletes2 = ParentCompletes() .set_name("parentcompletes2") .set_parent(self)
        
        timertrans5 = TimerTrans(0.5) .set_name("timertrans5")
        timertrans5 .add_sources(showemoji7) .add_destinations(playsound2)
        
        timertrans6 = TimerTrans(0.115) .set_name("timertrans6")
        timertrans6 .add_sources(playsound2) .add_destinations(glow6)
        
        nulltrans11 = NullTrans() .set_name("nulltrans11")
        nulltrans11 .add_sources(glow6) .add_destinations(showemoji8)
        
        nulltrans12 = NullTrans() .set_name("nulltrans12")
        nulltrans12 .add_sources(showemoji8) .add_destinations(movefor3)
        
        completiontrans6 = CompletionTrans() .set_name("completiontrans6")
        completiontrans6 .add_sources(movefor3) .add_destinations(glow7)
        
        nulltrans13 = NullTrans() .set_name("nulltrans13")
        nulltrans13 .add_sources(glow7) .add_destinations(showemoji9)
        
        nulltrans14 = NullTrans() .set_name("nulltrans14")
        nulltrans14 .add_sources(showemoji9) .add_destinations(movefor4)
        
        completiontrans7 = CompletionTrans() .set_name("completiontrans7")
        completiontrans7 .add_sources(movefor4) .add_destinations(glow8)
        
        nulltrans15 = NullTrans() .set_name("nulltrans15")
        nulltrans15 .add_sources(glow8) .add_destinations(showemoji10)
        
        nulltrans16 = NullTrans() .set_name("nulltrans16")
        nulltrans16 .add_sources(showemoji10) .add_destinations(movefor5)
        
        completiontrans8 = CompletionTrans() .set_name("completiontrans8")
        completiontrans8 .add_sources(movefor5) .add_destinations(statenode2)
        
        timertrans7 = TimerTrans(0.5) .set_name("timertrans7")
        timertrans7 .add_sources(statenode2) .add_destinations(glow9)
        
        nulltrans17 = NullTrans() .set_name("nulltrans17")
        nulltrans17 .add_sources(glow9) .add_destinations(parentcompletes2)
        
        return self
