from .nodes import *
from .transitions import *

class PickUp(ObjectSpecNode):
    def __init__(self, object_spec=None):
        super().__init__()
        self.object_spec = object_spec

    def start(self,event=None):
        if isinstance(event, DataEvent):
            spec = event.data
        else:
            spec = self.object_spec
        self.object = self.get_object_from_spec(spec)
        super().start(event)
        if self.object is None:
            self.post_failure()

    class Pickup_TurnToward(TurnToward):
        def start(self, event=None):
            self.object_spec = self.parent.object
            super().start(event)

    class Pickup_Forward(Forward):
        def start(self, event=None):
            robot_radius = 15
            dx = self.parent.object.x - self.robot.x
            dy = self.parent.object.y - self.robot.y
            self.distance_mm = sqrt(dx**2 + dy**2) - robot_radius
            super().start(event)

    def setup(self):
        #         turn: self.Pickup_TurnToward()
        #         turn =C=> forward
        #         turn =F=> ParentFails()
        # 
        #         forward: self.Pickup_Forward()
        #         forward =C=> ParentCompletes()
        #         forward =F=> ParentFails()
        
        # Code generated by genfsm on Mon Jan 13 01:23:25 2025:
        
        turn = self.Pickup_TurnToward() .set_name("turn") .set_parent(self)
        parentfails1 = ParentFails() .set_name("parentfails1") .set_parent(self)
        forward = self.Pickup_Forward() .set_name("forward") .set_parent(self)
        parentcompletes1 = ParentCompletes() .set_name("parentcompletes1") .set_parent(self)
        parentfails2 = ParentFails() .set_name("parentfails2") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(turn) .add_destinations(forward)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(turn) .add_destinations(parentfails1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(forward) .add_destinations(parentcompletes1)
        
        failuretrans2 = FailureTrans() .set_name("failuretrans2")
        failuretrans2 .add_sources(forward) .add_destinations(parentfails2)
        
        return self
